apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  parallelism: 5
  completions: 10
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: luksa/batch-job
